### ISSUE TITLE
Warframe-Launcher.bat

### ISSUE THREAD

**Issue by coreybruce** [GloriousEggroll/warframe-linux#1]
Warframe-Launcher.bat  file not launching and doesn't wget warframe file after deleting old warframe.msi file, all installed from Lutris.

I've made several reports on Lutris about the issue I was having now.

**Comment by GloriousEggroll** [comment]
I'm currently still editing it, was working to fix it yesterday, it's having problems using the Program Files (x86) path due to parenthesis in lutris

**Comment by GloriousEggroll** [comment]
I've edited the lutris installer to use C:\Program Files rather than C:\Program Files (x86), and made corresponding changes to the batch file and registry. I've also added lutris install notes telling the user not to use the (x86) path. Marking this resolved.

**Comment by coreybruce** [comment]
DO I need to reinstall Warframe? I copied all the new files in and the game still doesn't launch or show the bat window at all.

**Comment by GloriousEggroll** [comment]
make a backup of Warframe's "Downloaded" folder

remove it from Lutris, do a fresh install from lutris.

when the warframe launcher runs, choose C:\Program Files\Warframe for the install path, then close the launcher  when it gets to "checking for new content"

Right click Warframe in lutris, click "Browse Files"

Copy your backed up "Downloaded" folder into the folder that opens. 

Run warframe from lutris.

**Comment by coreybruce** [comment]
I didn't need to back up anything as I didn't haven't the game files download (since this issue happened and tried reinstalling) still can't get the game to run, I removed everything of the games files from Lutris than reinstalled it. Once done I ran it and it still doesn't show up and just says it quits not long after..

**Comment by GloriousEggroll** [comment]
Gah. This is because the new install script I published on lutris's website hasnt been approved yet. You'll have to wait until they approve the changes before installing it. I did the changes sunday morning.

**Comment by coreybruce** [comment]
Ok I got the update from you now that it's approved but I notice it's not opening as easily as it use and has asked me several times opening it where it wants to save tiles even tho I have already told it and get stuck on checking content.. how long is it suppose to do that exactly and is the bat window suppose to come up like it use to or be hidden now, I checked it and does have it open launcher.bet as I haven't touched anything in the fresh install.

**Comment by coreybruce** [comment]
Wait don't worry it did finish checking, i wasn't watching it so I don't know how long it took but I am noticing some graphical glitches now
