### ISSUE TITLE
Bug installing

### ISSUE THREAD

**Issue by privatefound** [GloriousEggroll/warframe-linux#11]
Unhandled exception: page fault on write access to 0x00000000 in 32-bit code (0x1075f55b).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:006b GS:0063
 EIP:1075f55b ESP:0449d0e8 EBP:0449d3f0 EFLAGS:00210246(  R- --  I  Z- -P- )
 EAX:00000000 EBX:07a3405c ECX:04c3df58 EDX:00000000
 ESI:04d19280 EDI:07a3405c
Stack dump:
0x0449d0e8:  0449d52f 07a3405c 00011102 0000000d
0x0449d0f8:  00000000 01015800 00000000 04c3df58
0x0449d108:  00000101 04cb7cd0 07a3405c 0000000d
0x0449d118:  00000001 00000000 01000101 0000000d
0x0449d128:  00000000 00000000 00000020 43140000
0x0449d138:  00000000 01000007 00000000 0449d44c
Backtrace:
=>0 0x1075f55b in libcef (+0x75f55b) (0x0449d3f0)
  1 0x1075de67 in libcef (+0x75de66) (0x0449d484)
  2 0x1076815b in libcef (+0x76815a) (0x0449d538)
  3 0x107010d4 in libcef (+0x7010d3) (0x0449d560)
  4 0x10701368 in libcef (+0x701367) (0x0449d580)
  5 0x106a45c8 in libcef (+0x6a45c7) (0x0449d58c)
  6 0x106abb69 in libcef (+0x6abb68) (0x0449d5ac)
  7 0x106ac0c8 in libcef (+0x6ac0c7) (0x0449d5e8)
  8 0x106ab807 in libcef (+0x6ab806) (0x0449d67c)
  9 0x106a796f in libcef (+0x6a796e) (0x0449d6c4)
  10 0x106a76f0 in libcef (+0x6a76ef) (0x0449d6f0)
  11 0x106fddbc in libcef (+0x6fddbb) (0x0449d704)
  12 0x107247f9 in libcef (+0x7247f8) (0x0449d77c)
  13 0x10724af2 in libcef (+0x724af1) (0x0449d7e4)
  14 0x106fdce5 in libcef (+0x6fdce4) (0x0449d7f8)
  15 0x106fee4c in libcef (+0x6fee4b) (0x0449d868)
  16 0x10725179 in libcef (+0x725178) (0x0449d8dc)
  17 0x10724af2 in libcef (+0x724af1) (0x0449d944)
  18 0x106fdce5 in libcef (+0x6fdce4) (0x0449d958)
  19 0x106fee4c in libcef (+0x6fee4b) (0x0449d9c8)
  20 0x10725179 in libcef (+0x725178) (0x0449da3c)
  21 0x10724af2 in libcef (+0x724af1) (0x0449daa4)
  22 0x106fdce5 in libcef (+0x6fdce4) (0x0449dab8)
  23 0x1072590d in libcef (+0x72590c) (0x0449dae4)
  24 0x107259c5 in libcef (+0x7259c4) (0x0449db44)
  25 0x10726de4 in libcef (+0x726de3) (0x0449dba0)
  26 0x10724ed6 in libcef (+0x724ed5) (0x0449dc1c)
  27 0x10724af2 in libcef (+0x724af1) (0x0449dc84)
  28 0x106fdce5 in libcef (+0x6fdce4) (0x0449dc98)
  29 0x1072590d in libcef (+0x72590c) (0x0449dcc4)
  30 0x107259c5 in libcef (+0x7259c4) (0x0449dd24)
  31 0x10726de4 in libcef (+0x726de3) (0x0449dd80)
  32 0x10724ed6 in libcef (+0x724ed5) (0x0449ddfc)
  33 0x10724af2 in libcef (+0x724af1) (0x0449de64)
  34 0x106fdce5 in libcef (+0x6fdce4) (0x0449de78)
  35 0x1072590d in libcef (+0x72590c) (0x0449dea4)
  36 0x107259c5 in libcef (+0x7259c4) (0x0449df04)
  37 0x10726de4 in libcef (+0x726de3) (0x0449df60)
  38 0x10724ed6 in libcef (+0x724ed5) (0x0449dfdc)
  39 0x10724af2 in libcef (+0x724af1) (0x0449e044)
  40 0x106fdce5 in libcef (+0x6fdce4) (0x0449e058)
  41 0x1071cd87 in libcef (+0x71cd86) (0x0449e118)
  42 0x10475f8e in libcef (+0x475f8d) (0x0449e174)
  43 0x104767c1 in libcef (+0x4767c0) (0x0449e268)
  44 0x1047adda in libcef (+0x47add9) (0x0449e298)
  45 0x1047a61f in libcef (+0x47a61e) (0x0449e2ec)
  46 0x105a66db in libcef (+0x5a66da) (0x0449e30c)
  47 0x113f4d90 in libcef (+0x13f4d8f) (0x0449e318)
  48 0x113e22ee in libcef (+0x13e22ed) (0x0449e34c)
  49 0x11645d50 in libcef (+0x1645d4f) (0x0449e444)
  50 0x10a6d2a7 in libcef (+0xa6d2a6) (0x0449e464)
  51 0x100c2540 in libcef (+0xc253f) (0x0449e4c4)
  52 0x11706350 in libcef (+0x170634f) (0x0449e570)
  53 0x11705e4d in libcef (+0x1705e4c) (0x0449e69c)
  54 0x116edaa4 in libcef (+0x16edaa3) (0x0449e6b8)
  55 0x11706486 in libcef (+0x1706485) (0x0449e6d4)
  56 0x100c2540 in libcef (+0xc253f) (0x0449e730)
  57 0x1007eef5 in libcef (+0x7eef4) (0x0449e79c)
  58 0x1007f898 in libcef (+0x7f897) (0x0449e8d0)
  59 0x100c16ff in libcef (+0xc16fe) (0x0449e904)
  60 0x100c141d in libcef (+0xc141c) (0x0449e924)
  61 0x1007ec85 in libcef (+0x7ec84) (0x0449e948)
  62 0x1009a769 in libcef (+0x9a768) (0x0449e970)
  63 0x100a3342 in libcef (+0xa3341) (0x0449e99c)
  64 0x100a34d3 in libcef (+0xa34d2) (0x0449e9d8)
  65 0x1007d3f7 in libcef (+0x7d3f6) (0x0449e9f8)
  66 0x7bc7d6bc (0x0449ea08)
  67 0x7bc805ff (0x0449eaf8)
  68 0x7bc7d69a (0x0449eb18)
  69 0x7bc8850f (0x0449f368)
  70 0xf759327a (0x0449f428)
0x1075f55b: movb	%al,0x00000000
Modules:
Module	Address			Debug info	Name (47 modules)
PE	  400000-  542000	Deferred        launcher
PE	10000000-12f89000	Export          libcef
PE	7ac10000-7ac1b000	Deferred        riched20
PE	7b410000-7b5ad000	Deferred        kernel32
PE	7bc10000-7bc14000	Deferred        ntdll
PE	7dce0000-7dce3000	Deferred        winejoystick
PE	7dcf0000-7dcfe000	Deferred        setupapi
PE	7dd60000-7dd64000	Deferred        rsaenh
PE	7e860000-7e8a1000	Deferred        crypt32
PE	7e940000-7e944000	Deferred        msftedit
PE	7e960000-7e964000	Deferred        iphlpapi
PE	7e980000-7e983000	Deferred        netapi32
PE	7e9b0000-7e9b3000	Deferred        secur32
PE	7e9f0000-7ea05000	Deferred        oleacc
PE	7ea40000-7ea43000	Deferred        dhcpcsvc
PE	7ea60000-7ea71000	Deferred        urlmon
PE	7eaf0000-7eaf3000	Deferred        userenv
PE	7eb10000-7eb15000	Deferred        jsproxy
PE	7eb30000-7eb36000	Deferred        winhttp
PE	7eb70000-7ec09000	Deferred        comdlg32
PE	7ec50000-7ec5a000	Deferred        winspool
PE	7ec90000-7ec93000	Deferred        usp10
PE	7ed00000-7ed03000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	7ed10000-7ed13000	Deferred        api-ms-win-core-localization-l1-C:\windows\system32\api-ms-win-core-localization-l1-2-1.dll
PE	7ed20000-7ed23000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	7ef50000-7ef53000	Deferred        api-ms-win-core-synch-l1-2-0
PE	7ef70000-7ef74000	Deferred        winex11
PE	7eff0000-7eff4000	Deferred        imm32
PE	7f1c0000-7f1c4000	Deferred        ws2_32
PE	7f200000-7f20a000	Deferred        mpr
PE	7f250000-7f254000	Deferred        psapi
PE	7f260000-7f278000	Deferred        wininet
PE	7f2d0000-7f2d3000	Deferred        wtsapi32
PE	7f2f0000-7f2f4000	Deferred        uxtheme
PE	7f320000-7f323000	Deferred        msimg32
PE	7f340000-7f36f000	Deferred        comctl32
PE	7f430000-7f439000	Deferred        msacm32
PE	7f460000-7f4d8000	Deferred        winmm
PE	7f520000-7f528000	Deferred        oleaut32
PE	7f650000-7f654000	Deferred        rpcrt4
PE	7f6e0000-7f6e8000	Deferred        ole32
PE	7f810000-7f818000	Deferred        shlwapi
PE	7f880000-7f9e0000	Deferred        shell32
PE	7fac0000-7fac4000	Deferred        advapi32
PE	7fb40000-7fb47000	Deferred        gdi32
PE	7fc70000-7fcac000	Deferred        user32
PE	7ffd0000-7ffd4000	Deferred        version
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000020    0
	0000001f    0
	00000014    0
	00000010    0
	0000000f    0
00000012 winedevice.exe
	0000001e    0
	00000019    0
	00000018    0
	00000013    0
0000001c plugplay.exe
	00000022    0
	00000021    0
	0000001d    0
00000023 explorer.exe
	0000002a    0
	00000029    0
	00000028    0
	00000027    0
	00000024    0
0000003f (D) C:\users\root\Local Settings\Application Data\Warframe\Downloaded\Public\Tools\Launcher.exe
	00000062    0
	00000061    0
	00000060    0
	0000005f    0
	0000005e    0
	0000005d    0
	0000005c    0
	0000005b    0
	0000005a    0
	00000059    0
	00000058    0
	00000057    0
	00000056    0 <==
	00000055    0
	00000054    0
	00000053    0
	00000052    0
	00000051    0
	00000050    0
	0000004f    0
	0000004e    0
	0000004d    0
	0000004c    0
	0000004b    0
	0000004a    0
	00000049    0
	00000048    0
	00000047    0
	00000046    0
	00000045    0
	00000044    0
	00000043    0
	00000042    0
	00000041    0
	00000040    0
System information:
    Wine build: wine-2.0.3 (Debian 2.0.3-1)
    Platform: i386
    Version: Windows XP
    Host system: Linux
    Host version: 4.9.0-kali3-amd64

**Comment by GloriousEggroll** [comment]
"Wine build: wine-2.0.3 (Debian 2.0.3-1)"

"Option B: Without Lutris:

**Install wine-staging 2.17 (or higher) for your linux distribution."**

**Comment by privatefound** [comment]
i cannot update it on kali

i try but i can't

**Comment by GloriousEggroll** [comment]
I recommend changing distro. Debian tends to be problematic when it comes to gaming with wine. Another debian user said they switched to sparky linux which is based on debian testing and everything worked
