### ISSUE TITLE
Error after starting launcher

### ISSUE THREAD

**Issue by Ragnar770** [GloriousEggroll/warframe-linux#14]
The game downloads fine and the launcher starts normally, downloads a 9mb update and then it spits out some errors in the terminal that I can't make out. Pastebin of terminal output and screenshot included.

https://i.imgur.com/5fyMYDN.png - clicking play doesn't do anything

https://pastebin.com/KD0Pd8T8 

Distro is a recent arch install with Budgie as my DE. I have all wine dependancies listed installed.

**Comment by igo95862** [comment]
I had similar issue and managed to fix it.

The message actually is 'Update DirectX'

This means that you are missing the wine's DirectX re-implementation. I fixed it by running following command:

`sudo pacman -S --needed giflib lib32-giflib libpng lib32-libpng libldap lib32-libldap gnutls lib32-gnutls mpg123 lib32-mpg123 openal lib32-openal v4l-utils lib32-v4l-utils libpulse lib32-libpulse alsa-plugins lib32-alsa-plugins alsa-lib lib32-alsa-lib libjpeg-turbo lib32-libjpeg-turbo libxcomposite lib32-libxcomposite libxinerama lib32-libxinerama ncurses lib32-ncurses opencl-icd-loader lib32-opencl-icd-loader libxslt lib32-libxslt libva lib32-libva gtk3 lib32-gtk3 gst-plugins-base-libs lib32-gst-plugins-base-libs vulkan-icd-loader lib32-vulkan-icd-loader cups samba dosbox`

**Comment by Ragnar770** [comment]
I finally got a chance to try again and installed the packages you listed but still got the same error.
