### ISSUE TITLE
Launcher doesn't update

### ISSUE THREAD

**Issue by lordcirth** [GloriousEggroll/warframe-linux#15]
Ubuntu 17.04, Lutris 4.14.
When running in a terminal from Lutris, it downloads the msi, runs the launcher which downloads a few MB, then quits with this:

```
C:\Program Files\Warframe>msiexec /i Warframe.msi 
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
$ [1207/223621:ERROR:main_delegate.cc(724)] Could not load locale pak for en-US
[1207/223621:ERROR:network_change_notifier_win.cc(155)] WSALookupServiceBegin failed with: 8
[1207/223621:ERROR:proxy_service_factory.cc(136)] Cannot use V8 Proxy resolver in single process mode.

$ 
```
There's no Launcher.exe.cpy or anything like that in Tools like the problem a while ago.  

Thank you for your work!

**Comment by NeroBurner** [comment]
have you installed the dependencies?
```
sudo apt-get install wine
sudo apt-get install wine-development
```

**Comment by lordcirth** [comment]
In 17.04, 'wine' is a virtual package:

lordcirth@lordcirth-K17:~$ sudo apt install wine wine-development
[sudo] password for lordcirth:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package wine is a virtual package provided by:
  wine-stable 1.8.7-1ubuntu1
  wine-development 2.0-3ubuntu1
You should explicitly select one to install.

E: Package 'wine' has no installation candidate

so I just ran:
lordcirth@lordcirth-K17:~$ sudo apt install wine-development

I had installed them, then uninstalled them apparently? Anyway I re-installed them and now the launcher with a installation location prompt appears for a few seconds before disappearing; I can't choose an install location.

Also, the script downloads Warframe.msi.tmp every time, which takes about 2m for me, which slows down testing.

C:\Program Files\Warframe>IF EXIST "Warframe.msi" GOTO FoundIt 

C:\Program Files\Warframe>start /b /wait "" "C:\Program Files\Warframe\Downloaded\Public\Warframe.exe" -silent -log:/Preprocessing.log -dx10:1 -threadedworker:0 -cluster:public -language:en -applet:/EE/Types/Framework/ContentUpdate 
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Path not found.

Terminal:
```
C:\Program Files\Warframe>start /b /wait "" "C:\Program Files\Warframe\Downloaded\Public\Warframe.exe" -silent -log:/Preprocessing.log -dx10:1 -threadedworker:0 -cluster:public -language:en -applet:/EE/Types/Framework/ContentUpdate 
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Path not found.


C:\Program Files\Warframe>msiexec /i Warframe.msi 
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
$ [1213/001441:ERROR:main_delegate.cc(724)] Could not load locale pak for en-US
[1213/001442:ERROR:network_change_notifier_win.cc(155)] WSALookupServiceBegin failed with: 8
[1213/001442:ERROR:proxy_service_factory.cc(136)] Cannot use V8 Proxy resolver in single process mode.
```

**Comment by lordcirth** [comment]
Ok, so I did that verbatim and nothing changed.  I even re-installed Warframe through Lutris.  Are there more packages I need?  Perhaps i386 versions of something?

**Comment by GloriousEggroll** [comment]
it's stating it can't find Warframe.exe, which should be located here inside warframe's prefix:
C:\Program Files\Warframe\Downloaded\Public\Warframe.exe"

**Comment by lordcirth** [comment]
Doesn't Warframe.exe only get created after the installer runs?

```
lordcirth@lordcirth-K17:/lPool/Shared/Games/Lutris/Games/warframe-2017-12-13-staging/drive_c/Program Files/Warframe/Downloaded/Public$ file Warframe.exe
Warframe.exe: PE32 executable (GUI) Intel 80386, for MS Windows
```

**Comment by GloriousEggroll** [comment]
I found the problem, looks like the shell script is removing the Downloaded folder for some reason.. which is not good, working on it now

**Comment by GloriousEggroll** [comment]
issue should be resolved now with both the lutris installer and the normal install script. The black box updater wasnt working because some initial files were missing. (eula files, directx cab files). It downloads these files automatically so I'd removed them in the past, but apparently warframe.exe checks these before even trying to update via black box. I've re-added them. I also cleaned up the registry files and fixed an issue with the launcher putting %USERNAME% in the registry instead of the actual user's username

**Comment by lordcirth** [comment]
It's installing!  I look forward to playing it tonight if nothing else goes wrong XD
Thank you for your work on this!

**Comment by lordcirth** [comment]
Ok, so after being away for many hours the black window seemed stuck at: "Preprocess 1300492741/... 7% complete".  When I closed it, the launcher appeared for a moment and then closed.  I'm trying it again now but it's going to take a long time.  My internet is very slow.  Perhaps I should have left it.

**Comment by lordcirth** [comment]
It seems to be stuck at 1% now.  Do you think that slow Internet alone could cause it to hang?

**Comment by lordcirth** [comment]
Ok, after another restart it's been stuck overnight at 4%.  Checking the Cache.Windows directory, it's 3.0GB and the size seems to rise slightly each time I run it - so I guess if I keep restarting it, it will finish eventually?  I've commented out the redownload of the launcher and binary to speed things up.

**Comment by lordcirth** [comment]
So after far too many restarts, I copied the Cache.Windows directory from a previous copy of the game and started the launcher.  That didn't help either; it got stuck at 4% again.

`C:\Program Files\Warframe>msiexec /i Warframe.msi 
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
$ [1227/140746:ERROR:main_delegate.cc(724)] Could not load locale pak for en-US
[1227/140746:ERROR:network_change_notifier_win.cc(155)] WSALookupServiceBegin failed with: 8
[1227/140746:ERROR:proxy_service_factory.cc(136)] Cannot use V8 Proxy resolver in single process mode.

$ 
`

Any ideas what's going wrong?

**Comment by lordcirth** [comment]
Well, I disabled the Lutris Process monitor after I saw that advice on a different issue, and it works now!  45 fps on a small map, but oh well.
