### ISSUE TITLE
Gallium-nine or DXVK?

### ISSUE THREAD

**Issue by fosspill** [GloriousEggroll/warframe-linux#19]
Hello!
Would this work with gallium nine or dxvk? Haven't had any luck yet myself, so if anyone has any ideas I'd love to hear them

**Comment by konserw** [comment]
I've tried gallium nine on Arch, wine 2.21; both 32-bit and 64-bit prefixes, using Radeon HD7850 on radeon kerenel / radeonsi mesa and failed :(
With my card performance without nine is not acceptable, so i'm back to windows dual-boot untill HW upgrade :(

**Comment by fosspill** [comment]
Works tolerable with Vega 56, but I'd love to use nine or DXVK. Next step would be to try DXVK, but I haven't been successful in trying to get it to run with this.

**Comment by GloriousEggroll** [comment]
gallium nine is for dx9 only, and does not solve the missing texture issue present in the dx9 version of the game. dxvk does not work for warframe yet
