### ISSUE TITLE
Better performance and no artifacting with Multi-Threaded Rendering enabled and less crashes with StrictDrawOrdering enabled

### ISSUE THREAD

**Issue by Vaerassar** [GloriousEggroll/warframe-linux#21]
When I play Warframe with the default configuration, my fps are between 5-10 and 60-80, and I crash quiet often. 

However, when I enable Multi-Threaded Rendering in the Warframe launcher, which as you know is disabled "to prevent crashing and for better performance", and especially in this case, because it "causes artifacting", my fps increase to between 15-20 and 100-120 and are always higher than with it disabled, and I don't have any artifacting. 

Moreover, when I enable StrictDrawOrdering in Regedit, which is disabled by default in the Wine prefix that Lutris creates for Warframe, I crash really less often, except in the Dojo in which I crash after about five minutes. Actually, Dojo aside, I crashed only a single time since I enabled StrictDrawOrdering. Without, I think I would have crashed a bit less than a dozen times.

As it is not the case with everyone, here are some informations about my computer if needed : 
System : Arch-Linux
Kernel : Linux-Zen
CPU : AMD FX-9370
GPU : AMD RX 580 (tried with both proprietary and open-source drivers, same results)

**Comment by GloriousEggroll** [comment]
the multi-threaded problem was for with dx9 on previous settings. there is still artifacting and bad performance in dx9 mode with multi-threading turned on, and crashing very often, although more so on the 64 bit client, not so much 32 bit
