### ISSUE TITLE
Updater.exe gets stuck at 51% (file B.CharacterCodesCacheDx9.toc refuses to download)

### ISSUE THREAD

**Issue by RiverMesa** [GloriousEggroll/warframe-linux#24]
When trying to install, the updater.exe gets stuck at 51% completion, specifically when trying to download the `$WARFRAME/Downloaded/Public/Cache.Windows/B.CharacterCodesCacheDx9.toc` file.

Which is, uh, kind of a showstopper problem, but I don't know if it's an issue on my end or some fluke on the server side, but no matter how many times I try to (re)run the installer/updater, it stops at specifically that one file.

System is Arch 64-bit (tried with both Wine-staging (2.21) and system Wine (3.3).
(Running from Lutris.)

**Comment by GloriousEggroll** [comment]
it's not getting stuck. this is a large file. just let it keep downloading. keep in mind warframe is 20gb in size.

**Comment by RiverMesa** [comment]
Hm, I see. It was just taking *way* longer than *any* other file so I just thought something was broken there.

Thanks.
