### ISSUE TITLE
Can't log in, connection times out

### ISSUE THREAD

**Issue by RiverMesa** [GloriousEggroll/warframe-linux#26]
So after resolving my issue in #24, I am now able to launch the game (in itself a huge success I'd say), however I'm not actually able to log in - the game tries to connect to the login API endpoint, but the connection times out after ~15 seconds, attempting to log in multiple times again (with the same result), ultimately resulting in a "Login failed, check your info" error message.

I don't know if it's something wrong with my Wine config (using wine-staging 2.21 as plain wine 3.3 doesn't seem to work properly), something to do with my networking, or something server-side, however it's been happening all day (and never once allowing me to log in), so I'm assuming it's not just a matter of the servers being overloaded or something.
I did also try to log in on the Warframe website, and it works there, so it's not a matter of my password/email being wrong either.

Some console logs that might be of note:
![image](https://user-images.githubusercontent.com/14968217/37157327-d14908c4-22e8-11e8-9c6e-bef32a385c8e.png)

For context, I'm assuming that my IP (`Host-IP`) should be visible there, but it isn't, and the local date (`Client-Date`) isn't correct either (I'm not in the GMT timezone), but I'm not sure if that's intentional, for all I know it is - doesn't look that way to me right now, though.

**Comment by GloriousEggroll** [comment]
wine-staging 3.3 and pba 3.3 both work
if you're using lutris, disable the process monitor and lutris runtimes
also I just updated updater.sh at around 4 am last night in attempt to fix an updating issue, so try replacing that as well in your warframe folder

**Comment by RiverMesa** [comment]
Tried with and without processor monitor and the runtime, updated to wine-staging 3.3, also updated the `updater.sh` file, and even tried overriding some libraries (a workaround briefly mentioned on WineHQ) - all to no avail at all. :slightly_frowning_face:

**Comment by GloriousEggroll** [comment]
have you double checked all wine dependencies?

**Comment by RiverMesa** [comment]
Gargh, in truth I was missing a few things, but that didn't seem to make any difference...

**Comment by GloriousEggroll** [comment]
do you happen to have anything like clamav running? had another guy who couldnt log into league of legends because of this

**Comment by RiverMesa** [comment]
Not that I can tell. Hrm...

**Comment by GloriousEggroll** [comment]
out of curiosity what distro? and what lutris version?

**Comment by RiverMesa** [comment]
Arch Linux, Lutris 0.4.14.

**Comment by GloriousEggroll** [comment]
I've just pushed some changes to updater.sh, please download updater.sh and place it in your Warframe folder and try again

**Comment by GloriousEggroll** [comment]
please let me know if this is resolved with the latest updater.sh. i will close if so.

**Comment by GloriousEggroll** [comment]
closing, after no update on this. script has heavily changed also.

**Comment by RiverMesa** [comment]
Ah, sorry, I forgot about this for some time.
I'll see if things are still wonky and report back. (Fingers crossed, the updates to the script look at least somewhat promising.)
