### ISSUE TITLE
Problems with installation - Missing files?

### ISSUE THREAD

**Issue by Estard** [GloriousEggroll/warframe-linux#29]
Hello,
I just tried to make a fresh install of the game but the game wouldn't launch.
The console output states that it wasn't able to find /drive_c/Program Files/Warframe/Downloaded/Public

Creating that folder manually the launcher runs into other problems where he isn't able to find many files in /Downloaded/Public/Cache.Windows
but most problematic is the error message that he is unable to to load PhysX3Common_x64.dll and find the according libraries after that he just cleans up and exits the launching.
I then noticed that there was a complete /Downloaded/Public folder in the patch-1 branch but not in the master branch, so I tried copying the missing files from there which results in actually downloading files by the script.
But even then he has the same problem with the PhysX component,
my guess is that it has to do with them being not 64bit but 32bit variants, but I ran out of ideas on how to resolve this problem as even trying to install PhysX with winetricks and with the the official installer but both approaches didn't work out.
I also tried to activate the launcher directly skipping the error message, but then the launcher doesn't seem to be able to make a functional install either and just tells after half an hour me that my downloaded data is corrupted.

I hope you can help me with this somehow,
kind regards

**Comment by NeroBurner** [comment]
how did you install warframe, with `install.sh` or with lutris?

**Comment by Estard** [comment]
I used lutris to install warfame

**Comment by Estard** [comment]
It seems that with the changes to update.sh the game now is installing correctly and creating the necessary folders and downloading the needed components.

thanks for your efforts
