### ISSUE TITLE
Game crashed just before the login screen 

### ISSUE THREAD

**Issue by znekk** [GloriousEggroll/warframe-linux#3]
So everything went fine until the game crashed before login. Now the launcher won't work : When I type "warframe", the script does it's usual update of .msi and finishes but then nothing happens. The black box does pop up at the beggining but then closes. 

When the launcher started I looked at settings and noticed directx10 ticked, is it related ?

**Comment by GloriousEggroll** [comment]
The dx10 and Dx11 ticks are fine.its meant to be run in Dx11. Please make sure you have all wine dependencies installed.

When the black box opens then closes it's just verifying you have all the game files before trying to run Warframe.msi

**Comment by znekk** [comment]
Alright, reinstalled wine, it's alright now.

**Comment by znekk** [comment]
Nevermind. This is what happens : 
15.805 Error [Info]: GPF

Application error messages:
NidusReleaseAlchemyChair.lua
CheckForFeature
PlayerShip.lua
Christmasify
PlayerShip.lua
Christmasify
Hub.lua
PlayerShip

15.805 Script [Info]: Starting Vignette close animation...
15.805 Script [Info]: MainMenu::SetCurrentState(0)
15.805 Script [Info]: SetCurrentState checking states: nil currentState: 0
Error [Debug]: Loaded unexpected version of dbghelp.dll from C:\windows\system32\dbghelp.dll
15.805 Script [Info]: SetQuitVisible(true)
15.807 Script [Info]: Background::ForceClearChildMovie()
wine: cannot find L"C:\\windows\\system32\\dxdiag.exe"
Error [Error]: Could not write DXDiag

Same as before, managed to get to loading screen before the login screen. I guess I'm missing game files. I'm trying to use some of the files from my win10 install though, that might be the problem ?

**Comment by GloriousEggroll** [comment]
you're missing wine dependencies. I had the same problem on my second machine where it would crash right before the login screen about 3/4 through the loading.

**Comment by znekk** [comment]
Ah, right... going to try that then. The dependencies are a bit of a headache really ! :D I'm on Fedora by the way.

**Comment by znekk** [comment]
Still not working. Same problem as before, crashing before login screen. I've added more dependencies, not sure what to do now though. Also, the lauchner works only once, it doesn't work again after a crash. I have to uninstall/reinstall then.

**Comment by GloriousEggroll** [comment]
are you using lutris? if so try enabling process monitor. seems there is a bug with lutris atm with the process monitor where it needs to be enabled otherwise warframe freezes within 10 seconds of loading
