### ISSUE TITLE
I can't install it. Loaded unexpected version of dbghelp.dll from C:\windows\system32\dbghelp.dll

### ISSUE THREAD

**Issue by Kerrung** [GloriousEggroll/warframe-linux#34]
Hi! Thank you very much for your work!
But, unfortunately, it's don't work for me. I can't install it.

4.014 Error [Info]: GPF
Error [Debug]: Loaded unexpected version of dbghelp.dll from C:\windows\system32\dbghelp.dll

Script stops here.

**Comment by GloriousEggroll** [comment]
if you're using wine-staging upstream, please change to staging 3.4. current upstream is broken due to swapchain/vsync changes

**Comment by Kerrung** [comment]
thank you
