### ISSUE TITLE
Delete the unnecessary line from install.sh

### ISSUE THREAD

**Issue by Kerrung** [GloriousEggroll/warframe-linux#35]
Originally:

echo "[Desktop Entry]" > warframe.desktop
	echo "Encoding=UTF-8" >> warframe.desktop
	echo "Name=Warframe" >> warframe.desktop
	echo "GenericName=Warframe" >> warframe.desktop
	echo "Warframe" >> warframe.desktop
	echo "Exec=/usr/bin/warframe \"\$@\"" >> warframe.desktop
	echo "Icon=/usr/share/pixmaps/warframe.png" >> warframe.desktop
	echo "StartupNotify=true" >> warframe.desktop
	echo "Terminal=false" >> warframe.desktop
	echo "Type=Application" >> warframe.desktop
	echo "Categories=Application;Game" >> warframe.desktop

This line is superfluous:
echo "Warframe" >> warframe.desktop

**Comment by Kerrung** [comment]
vcrun2013 does not need to be installed anymore. Wine Staging can now work without it.

**Comment by Kerrung** [comment]
wf.reg
[HKEY_CURRENT_USER\Software\Wine\DllRedirects]
 "wined3d"="wined3d-csmt.dll"
does not need to be installed anymore. This causes rendering problems but does not improve fps performance. 
Since Wine 3.3 now has its own separate implementation of CSMT different from Wine Staging and enabled by default. If it is enabled, it fixes rendering problems.

**Comment by Kerrung** [comment]
wf.reg

[HKEY_CURRENT_USER\Software\Wine\Direct3D]
"OffscreenRenderingMode"="fbo"
"RenderTargetLockMode"="readtex"
"VideoMemorySize"="2048"

Not all have 2GB VRAM.
Many users have 4GB or 8GB, but probably will not be able to use the full amount of VRAM because of this artificial limitation.

**Comment by GloriousEggroll** [comment]
the videomemorysize limitation was an old registry entry used for dx9 mode. also previously the game would not launch without csmt enabled, i've checked and it does indeed run without it now. I'll get these cleaned up

**Comment by Kerrung** [comment]
How do I switch to d3d11 mode to use DXVK?
Your script starts the game only in d3d9 mode and unfortunately I did not manage to get the game started in d3d11 mode. In d3d9 mode, the game is unstable and I see the issues of rendering lags, but in d3d11 mode everything works well. I learned this when I ran the game through the official launcher, but it works unstably.

**Comment by GloriousEggroll** [comment]
I've been made aware from another user that the script runs Warframe.exe, when it should run Warframe.x64.exe. I'll take a look at this later tonight. Lutris detects and runs Warframe.x64.exe properly. in the meantime if you adjust the script to use Warframe.x64.exe it should launch in d3d11 mode

**Comment by Kerrung** [comment]
Thank you
