### ISSUE TITLE
Warframe servers don't trust User-Agent

### ISSUE THREAD

**Issue by Urumasi** [GloriousEggroll/warframe-linux#36]
Attempting to run the update script causes the following error
> curl: (56) Recv failure: Connection reset by peer

Connection reset by peer error persists even after switching to wget, seems to be caused by server not trusting wget/curl User-Agent.
This issue can be solved by adding the following User-Agent parameters:
```bash
curl -A Mozilla/5.0 ...
wget -U Mozilla/5.0 ...
```

**Comment by GloriousEggroll** [comment]
updated, should work now, thanks for the heads up
