### ISSUE TITLE
When running installer i get "cannot find ncurses (libncurses.so.5)

### ISSUE THREAD

**Issue by CLNinja** [GloriousEggroll/warframe-linux#37]
Title says it all.

**Comment by GloriousEggroll** [comment]
This is a wine dependency. Read the first sentence in the README.

**Comment by CLNinja** [comment]
I've gotten out of wine dependency hell multiple times now and on a reinstall of the launcher and warframe inside of lutris it tells me it cannot find it yet it's installed.

**Comment by GloriousEggroll** [comment]
if the lutris runtime is enabled, disable it
