### ISSUE TITLE
Launcher just checks for updates and doesn't ever start the game.

### ISSUE THREAD

**Issue by thegriffindude** [GloriousEggroll/warframe-linux#39]
Also when I go to the .exe's the terminal output I get is "wine: Bad EXE format"

**Comment by GloriousEggroll** [comment]
I don't have this problem at all. Not in lutris or via the script itself.
Need to know:
-wine version
-have you installed all wine dependencies?
-did you do a full install or use a pre-existing install?
-did you let the update complete?

If you don't see "launching warframe" then it never finished updating. Updating takes a long while as the game is roughly 20gb.

**Comment by thegriffindude** [comment]
I tried the Lutris method and it worked flawlessly.
You da man, man.
