### ISSUE TITLE
License

### ISSUE THREAD

**Issue by justinbrewer** [GloriousEggroll/warframe-linux#42]
Any thoughts on putting a license on this project?

**Comment by GloriousEggroll** [comment]
I plan on adding gpl v2 to it, but I need to change it so it doesnt rely on warframe.png as the warframe logo is not my property

**Comment by GloriousEggroll** [comment]
resolved 049501873791f2d653e6a385d659bfbad4f5252d
now downloads warframe.png instead of storing it in repo.
