### ISSUE TITLE
Warframe crash during fight

### ISSUE THREAD

**Issue by NeroBurner** [GloriousEggroll/warframe-linux#43]
wine 3.5-staging

sometimes I'm able to play 10 minutes, sometimes the game crashes in the first encounter

[Preprocessing.log](https://github.com/GloriousEggroll/warframe-linux/files/1886179/Preprocessing.log)

edit: continuation of https://github.com/GloriousEggroll/warframe-linux/issues/40

**Comment by Kerrung** [comment]
Try DXVK
https://github.com/doitsujin/dxvk

**Comment by GloriousEggroll** [comment]
I've already suggested that you install missing winetricks. Myself and Kerrung also suggested you try DXVK. if you aren't going to take advice then stop opening new issues. Closing.

**Comment by NeroBurner** [comment]
I did try installing the missing winetricks. Did not change the crashes. I also had the crashes with dxvk and wine 3.4. I will try tomorrow with wine 3.5 and dxvk
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NeroBurner** [comment]
wine-3.5 (Staging)
dxvk-bin 0.41-1 from AUR

@GloriousEggroll all missing winetricks installed, new log with dxvk, created a fresh bottle for dxvk
still when playing Pavlov on Lua the game crashes on the first enemy I encounter


[Preprocessing-dxvk.log](https://github.com/GloriousEggroll/warframe-linux/files/1887181/Preprocessing-dxvk.log)

**Comment by GloriousEggroll** [comment]
sorry, I don't know.
I suggest posting a bug report on winehq, as nothing on my launcher will solve the issue at this point

**Comment by GloriousEggroll** [comment]
hey Nero can you do me a favor? try changing the script so it uses just Warframe.exe, not Warframe.x64.exe. I feel this might be part of the crash issue but im not sure.

**Comment by GloriousEggroll** [comment]
mmm. i dont think you should have to switch. can you try 32 bit with dxvk?. I've updated my dxvk-tools to allow 32 bit and 64 bit dxvk to work in 64 bit prefix. also, you dont have to make a clean 32 bit prefix to run 32 bit warframe, you can run it in 64 bit prefix if your wine is cross compiled.

**Comment by NeroBurner** [comment]
I have wine-staging from the arch repositories. Is that cross compiled?

I will try to play the crashing Lua level with dxvk in 32bit mode in the evening.

Can you have dxvk 32 and 64 bit in one wine bottle? I'll have a look at your dxvk-tools
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NeroBurner** [comment]
I tried all combinations I could think of. All logs are from playing the first few minutes of Pavlov on Lua

the following wine prefix and warframe version are the same (a bottle for each WINEARCH), vulkan is installed using `winetricks` (installs `VulkanSDK-1.0.68.0-Installer.exe`), dxvk is 0.41 from AUR (dxvk-bin):
- amd64 no dxvk: no crash [Preprocessing_64bit_no_dxvk_no_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1890867/Preprocessing_64bit_no_dxvk_no_crash.log)
- amd64 dxvk: crash, error reporting tool [Preprocessing_64bit_dxvk_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1890866/Preprocessing_64bit_dxvk_crash.log)
- i386 no dxvk: no crash [Preprocessing_32bit_no_dxvk_no_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1890865/Preprocessing_32bit_no_dxvk_no_crash.log)
- i386 dxvk: crash, game completely freezes [Preprocessing_32bit_dxvk_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1890863/Preprocessing_32bit_dxvk_crash.log)

The following are all win64 WINEARCH prefixes, the first with 32bit Warframe exe, the second with 64bit warframe exe, your tools install `VulkanSDK-1.0.51.0-Installer.exe`
- amd64 prefix, dxvk-tools to install vulkan+dxvk, Warframe.exe: crash, total game freeze [Preprocessing_32bit_dxvk-tools_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1890930/Preprocessing_32bit_dxvk-tools_crash.log) 
- amd64 prefix, dxvk-tools to install vulkan+dxvk, Warframe.x64.exe: flickering textures, 
short game freezes (maybe dxvk shader compile), crash, error reporting tool [Preprocessing_64bit_dxvk-tools_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1890916/Preprocessing_64bit_dxvk-tools_crash.log)

Regardless of the method to install vulkan (winetricks or dxvk-tools), for me Warframe crashes with dxvk on this misson on Lua. On 32bit warframe just freezes, on 64bit the error reporting tool is started

Can you think of something else I could try? I hope you can find something. Maybe it is just my AMD Ryzen 1700 or my AMD RX570 GPU (open source `amdgpu` driver)?

**Comment by GloriousEggroll** [comment]
if you're on arch and using dxvk, you'll want to be on llvm5. llvm6 is a hang-machine (lots of problems). youll also want mesa 18 at least, preferably mesa-git

**Comment by NeroBurner** [comment]
- [ ] llvm5: should I install llvm50 from the AUR? Do you know how llvm has an influence on Warframe? dxvk is built with mingw, so gcc. Maybe wine is built with llvm/clang?
- [x] mesa: installed 18.0.0-2

**Comment by GloriousEggroll** [comment]
wine has nothing to do with llvm  
llvm 6 in general causes hangs in a lot of games, especially with dxvk, as it was recently released and still has a lot fo bugs.  

I think that llvm5 package on the aur is missing some things and it doesnt have a 32 bit package either.
You also will need to compile mesa against llvm 5, so using a precompiled mesa package will not work.  

Here's how to do it on arch:  
1. download the llvm 5 packages from arch's archive into a folder:  
https://archive.archlinux.org/packages/  
see picture attached for the packages you need. You will also need to remove the compiler-rt package and clang if it asks.  
![llvm5](https://user-images.githubusercontent.com/11287837/38515281-c21c4244-3c01-11e8-985a-3a58d4295ef3.png)  

Once you have them all downloaded and remove compiler-rt via sudo pacman -R compiler-rt, open a terminal and cd into the folder, then install them all at once with:  
sudo pacman -U *  

2. When that finishes, download the mesa-git and lib32-mesa-git snapshots from the aur and extract them:  
wget https://aur.archlinux.org/cgit/aur.git/snapshot/mesa-git.tar.gz  
wget https://aur.archlinux.org/cgit/aur.git/snapshot/lib32-mesa-git.tar.gz  
tar -xvzf mesa-git.tar.gz  
tar -xvzf lib32-mesa-git.tar.gz  

Then you'll need to modify both PKGBUILDs. Go into each extracted folder, and open the PKGBUILD with a text editor. remove all "-svn" references from any package names and save the PKGBUILD. This will allow it to use normal llvm instead of llvm-svn  

now compile and install both packages:  
cd mesa-git  
makepkg -csi  
cd ..  
cd lib32-mesa-git  
makepkg -csi

**Comment by NeroBurner** [comment]
can't install mesa-git
```
==> Finished making: mesa-git 18.1.0_devel.101504.d66dc34316-1 (Mon Apr  9 22:58:01 CEST 2018)
==> Installing mesa-git package group with pacman -U...
loading packages...
resolving dependencies...
looking for conflicting packages...
:: mesa-git and mesa are in conflict. Remove mesa? [y/N] y
:: mesa-git and vulkan-radeon are in conflict. Remove vulkan-radeon? [y/N] y
:: mesa-git and libva-mesa-driver are in conflict. Remove libva-mesa-driver? [y/N] y
:: mesa-git and mesa-vdpau are in conflict. Remove mesa-vdpau? [y/N] y
:: mesa-git and wayland are in conflict. Remove wayland? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: gst-plugins-bad: removing wayland breaks dependency 'wayland'
:: gtk3: removing wayland breaks dependency 'wayland'
:: lib32-wayland: removing wayland breaks dependency 'wayland'
:: libva: removing wayland breaks dependency 'wayland'
:: mpv: removing wayland breaks dependency 'wayland'
==> WARNING: Failed to install built package(s).
==> Cleaning up...
```

**Comment by GloriousEggroll** [comment]
oh ffs. he updated it 4 days ago to conflict with wayland. it doesnt conflict with wayland.
remove  'wayland<1.14.93' from the conflicts list in the PKGBUILD

I also forgot to mention you want to use RADV_DEBUG=nohiz with warframe and dxvk

**Comment by NeroBurner** [comment]
Thanks, I'll try in the evening

So I'd start warframe wirth `RADV_DEBUG=nohiz wine64 Warframe.x64.exe  ...`? Could you explain what this does?

Thanks for the help :)

On April 10, 2018 2:34:19 AM GMT+02:00, Thomas Crider <notifications@github.com> wrote:
>oh ffs. he updated it 4 days ago to conflict with wayland. it doesnt
>conflict with wayland.
>remove  'wayland<1.14.93' from the conflicts list in the PKGBUILD
>
>I also forgot to mention you want to use RADV_DEBUG=nohiz with warframe
>and dxvk
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GloriousEggroll/warframe-linux/issues/43#issuecomment-379936310

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by GloriousEggroll** [comment]
Google can do that. Or you can try it and find out yourself. I've already explained enough

**Comment by NeroBurner** [comment]
Yes you have, and I'm very grateful to you

I've successfully compiled and installed mesa-git, lib32-mesa-git and wayland-git.

Unfortunately 64bit with dxvk-tools and `nohiz` still crashes 
[Preprocessing_64bit_dxvk-tools_mesa-git_crash.log](https://github.com/GloriousEggroll/warframe-linux/files/1895974/Preprocessing_64bit_dxvk-tools_mesa-git_crash.log)

**Comment by GloriousEggroll** [comment]
dont use warframe.x64.exe. i changed the script to use warframe.exe with 64 bit prefix

**Comment by GloriousEggroll** [comment]
also I would get the most recent nightly for dxvk as yesterday's commit removed pipeline cache and fixes a lot of stuttering

**Comment by NeroBurner** [comment]
dxvk-tools with 32bit warframe in 64bit prefix works :+1: 

I was nearly able to complete the Lua mission. At one point the game just froze (3rd spy target :sob: ), but this seems to be a different issue

**Comment by GloriousEggroll** [comment]
With latest dxvk build I just ran around cetus and outside cetus with maxed settings except using MSAA and disable depth of field and motion blur. rock solid 60fps (on vega 64). only freezes/stutters I got were in between loading areas

**Comment by NeroBurner** [comment]
I just got a freeze. Here are my EE.cfg settings. Have I something enabled, that I should not have?
```
[Windows_Config,/EE/Types/Base/Config]
Stats.Visible=1
Graphics.AnisotropicFiltering=AF_16X
Graphics.AntiAliasing=AA_FXAA
Graphics.AutoDetectGraphicsSettings=0
Graphics.BlurLocalReflections=0
Graphics.Borderless=1
Graphics.DynamicResolution=DYNRES_USER
Graphics.EnableDOF=0
Graphics.EnableMotionBlur=0
Graphics.EnableTessellation=0
Graphics.EnableVolumetricLighting=0
Graphics.GeometryDetail=GD_HIGH
Graphics.LocalReflections=0
Graphics.MaxFrameRate=200
Graphics.ParticleSysQuality=PQ_HIGH
Graphics.ShadowQuality=SQ_HIGH
Graphics.TextureQuality=TQ_HIGH
Graphics.TrilinearFiltering=TF_ON
Graphics.VSyncMode=VSM_NEVER_SYNC
```

**Comment by GloriousEggroll** [comment]
try turning vsync on. it may have a problem keeping up with the frame output

**Comment by NeroBurner** [comment]
will try in the evening. Reporting back as soon as possible

**Comment by NeroBurner** [comment]
still no luck, but again thank you for your time and all your tipps
