### ISSUE TITLE
Crashes using your script

### ISSUE THREAD

**Issue by Endoxx** [GloriousEggroll/warframe-linux#44]
I want to add that i followed your guide on How to get through wine dependencie hell but it still crashes.

Here is the log:
https://pastebin.com/yhc85w5A

**Comment by GloriousEggroll** [comment]
can you try adding the following library overrides in winecfg:  

xaudio2_0 native, builtin  
xaudio2_1 native, builtin  
xaudio2_2 native, builtin  
xaudio2_3 native, builtin  
xaudio2_4 native, builtin  
xaudio2_5 native, builtin  
xaudio2_6 native, builtin  
xaudio2_7 native, builtin  
xaudio2_8 native, builtin  
xaudio2_9 native, builtin

**Comment by Endoxx** [comment]
Added them but it still crashes
Log:
https://pastebin.com/wXd0Rrji

**Comment by GloriousEggroll** [comment]
this is a shot in the dark, but in the warframe/downloaded/public/drivers/directx9 folder there should be a DXSETUP.exe, can you run this on the prefix?   

WINEARCH=win64 WINEPREFIX=/path/to/prefix wine64 DXSETUP.exe

**Comment by justinbrewer** [comment]
On Lutris, the Wine prefix can be found by right clicking Warframe -> Configure -> Game options. Unless you've changed it, it's `~/Games/warframe`.

**Comment by Endoxx** [comment]
Still doesn't work.

Here is the output after running your suggestion:


`000b:fixme:winediag:start_process Wine Staging 3.5 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
002a:err:module:import_dll Library RASAPI32.dll (which is needed by L"C:\\windows\\system32\\gecko\\2.47\\wine_gecko\\xul.dll") not found
0035:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
0035:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0035:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
002a:err:module:import_dll Library RASAPI32.dll (which is needed by L"C:\\windows\\system32\\gecko\\2.47\\wine_gecko\\xul.dll") not found
Could not load wine-gecko. HTML rendering will be disabled.
003d:err:module:import_dll Library RASAPI32.DLL (which is needed by L"C:\\windows\\syswow64\\gecko\\2.47\\wine_gecko\\xul.dll") not found
003f:fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
003f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
003f:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
003d:err:module:import_dll Library RASAPI32.DLL (which is needed by L"C:\\windows\\syswow64\\gecko\\2.47\\wine_gecko\\xul.dll") not found
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/michi/Games/warframe' has been updated.
wine: cannot find L"C:\\windows\\system32\\DXSETUP.exe"`

**Comment by GloriousEggroll** [comment]
please use something to fix your log
also you need to be in the folder that contains DXSETUP.exe via terminal in order to run it. read the error.
"wine: cannot find L"C:\\windows\\system32\\DXSETUP.exe"

.. that's because it doesnt exist there.

**Comment by Endoxx** [comment]
Alright I'll continue using pastebin (seems to work better) 

Output after running it in the correct folder (i hope):

https://pastebin.com/QURt69EW

**Comment by GloriousEggroll** [comment]
if it finished try running warframe again.

**Comment by Endoxx** [comment]
Tried and crashed again

https://pastebin.com/iwU1hC0s

**Comment by GloriousEggroll** [comment]
sorry, I really don't know. I don't have this crash on my system at all.

**Comment by Endoxx** [comment]
It's alright i'll try again in a few weeks and hope it resolves itself somehow

**Comment by Kerrung** [comment]
Report your Wine bugs here, please:
https://bugs.winehq.org

**Comment by Endoxx** [comment]
Allright thx for reminding me, will do.
