### ISSUE TITLE
Staging patches required

### ISSUE THREAD

**Issue by lesderid** [GloriousEggroll/warframe-linux#46]
Which wine-staging patchsets are required to run Warframe?

I can't use all of wine-staging since this breaks another game, so I'd like to build a version with only the patches necessary for Warframe.

**Comment by GloriousEggroll** [comment]
what patch is breaking another game? I haven't come across any games being broken. The only exception is you need to se the pba heap sizes for 32 bit games

**Comment by GloriousEggroll** [comment]
yes, xaudio2 had a bug which I patched in staging to prevent a crash, but it still needs the override. I'd actually like to know what staging patch causes the stuttering in ffxiv. ffxiv dx11 also works with dxvk now, but again the stutter issue.

**Comment by lesderid** [comment]
Yeah, I just use wine 3.4 vanilla with staging Vulkan patch applied for FFXIV with dxvk. This works fine without any stuttering issues. I'm not subscribed right now, but I'll try to find which patch causes the stuttering when I resub.

**Comment by lesderid** [comment]
Yeah sorry I was mistaken, I was using wine 3.5 vanilla for FFXIV I believe. (my Wine builds are a bit of a mess to manage >.<)

**Comment by GloriousEggroll** [comment]
I'd prefer to use staging precisely for that reason - to find what patches are causing problems and correct them before upstreaming (I am one of the staging maintainers.)

**Comment by lesderid** [comment]
For a wine-staging maintainer that's probably a good approach. :-)

Anyway, Warframe seems to run with  `patchinstall.sh include-winsock wininet-Cleanup wininet-Http_Decoding wininet-Internet
    CrackUrlW wininet-Internet_Settings winhttp-Accept_Headers ws2_32-APC_Performance ws2_32-Connect_Time ws2_32-Tran
    smitFile ws2_32-WSACleanup ws2_32-getaddrinfo ws2_32-getsockopt winecfg-Libraries winecfg-Staging`.

I'm not sure which one is are the one that's needed, but I at least don't think these should cause stuttering in FFXIV. (I'm not sure when I'll resub, so it might be worth checking yourself which patch breaks FFXIV if it's high-priority)

**Comment by GloriousEggroll** [comment]
i dont think the wininet, winhttp, or winsock patches are necessary, dont know about the others
