### ISSUE TITLE
Installing Warframe on Solus

### ISSUE THREAD

**Issue by Bios-Marcel** [GloriousEggroll/warframe-linux#48]
Hey,

I have tried installing Warframe on Solus, but due to the absence of `xterm` i can't install it. 
Sadly Solus doesn't support xterm as of now.
Is there an easy way of changing the used terminal?

Regards Marcel

**Comment by Bios-Marcel** [comment]
Okay, i kinda opened this issue out of confusion, i didn't realize that `Updater.exe` isn't actually a windows executable. I have now replaced the xterm calls with gnome-terminal terms and i'd like to make a pull request that uses gnome-terminal as a fallback in case xterm doesn't exist.
In my case i can't get xterm unless i build it myself, which i terribly failed at and most beginners will probably fail at aswell.

**Comment by Bios-Marcel** [comment]
I ended up replacing all xterm calls with `bash ./file.sh $@`, i assume that isn't an option for you since it won't open an additional window, correct? But wouldn't it be good to have a fallback in case xterm doesn't exist?

**Comment by GloriousEggroll** [comment]
I'm not using gnome terminal as it's specific to gnome. literally almost
every distro h as xterm because almost every distro uses X. Why solus does
not have xterm is beyond me.

**Comment by BigETI** [comment]
`xterm` is not installed at all distributions that run X11 context. It's just the standard terminal emulator for the X Window System.

**Comment by Bios-Marcel** [comment]
After going through dependency hell, i was able to build xterm. The bash calls were indeed trash, dunno why.
