### ISSUE TITLE
Application could not be started

### ISSUE THREAD

**Issue by HaZine** [GloriousEggroll/warframe-linux#5]
Installed the game using wine-staging and your wine wrapper repo. When I typed warframe in console the console outputs:

Warframe.msi         46%[========>           ]  16.73M  1.91MB/s    eta 10s    
C:\Program Files\Warframe>GOTO CheckForFile 

C:\Program Files\Warframe>IF EXIST "Warframe.msi" GOTO FoundIt 

C:\Program Files\Warframe>start /b /wait "" "C:\Program Files\Warframe\Downloaded\Public\Warframe.exe" -log:/Preprocess.log -threadedworker:1 -cluster:public -language:en -applet:/EE/Types/Framework/ContentUpdate 
Warframe.msi         47%[========>           ]  17.22M  1.93MB/s    eta 10s    Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Invalid parameter.

Then it just finish updating the .msi but then does nothing.

**Comment by HaZine** [comment]
Installed the game again, this time using Lutris. The game worked fine but there was the graphical glitches. I made changes to the registry file and install.sh, then I enabled CSMT in winecfg. Tried running the game again. The black box popped up then disappeared after 2 or 3 seconds, and Lutris says "Game has quit".

**Comment by GloriousEggroll** [comment]
In regards to crashing, make sure of a few things:
1. Your lutris version is 0.4.13 or higher
2. You have -all- wine dependencies installed. I had several crashing problems until I made sure all wine dependencies were installed.
3. Disable In-game microphone

In regards to graphical glitches:
Remove the mesa_glthread environment variable in the shell script or in lutris environment variables for warframe

**Comment by HaZine** [comment]
Sorry, went away for a few days, couldn't reply. I checked, the dependencies are there. But everytime I start up warframe, there is still a chance that the black box will pop up but no actual launcher. I'm running Linux lite on the 16.0.4 LTS, if that's helpful at all.

**Comment by GloriousEggroll** [comment]
Updated, method b needed a 32 bit prefix, just tested, could you try again with method b?

**Comment by HaZine** [comment]
hans@hans-Lenovo-ideapad-Y700-Touch-15ISK:~$ WINEPREFIX=~/.wine32 WINEARCH=win32 warframe


C:\Program Files\Warframe>:CheckForFile 

C:\Program Files\Warframe>IF EXIST "Warframe.msi" GOTO FoundIt 

C:\Program Files\Warframe>REM If we get here, the file is not found. 

C:\Program Files\Warframe>REM Wait 60 seconds and then recheck. 

C:\Program Files\Warframe>REM If no delay is needed, comment/remove the timeout line. 

C:\Program Files\Warframe>ping -n 10 0.0.0.0 > nul 
--2017-10-21 23:33:27--  http://content.warframe.com/dl/Warframe.msi
Resolving content.warframe.com (content.warframe.com)... 205.185.216.42, 205.185.216.10
Connecting to content.warframe.com (content.warframe.com)|205.185.216.42|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36442112 (35M) [application/octet-stream]
Saving to: ‘Warframe.msi’

Warframe.msi          5%[>                   ]   1.75M   185KB/s    eta 2m 37s 
C:\Program Files\Warframe>GOTO CheckForFile 

C:\Program Files\Warframe>IF EXIST "Warframe.msi" GOTO FoundIt 

C:\Program Files\Warframe>start /b /wait "" "C:\Program Files\Warframe\Downloaded\Public\Warframe.exe" -log:/Preprocess.log -threadedworker:1 -cluster:public -language:en -applet:/EE/Types/Framework/ContentUpdate 
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: Invalid parameter.


C:\Program Files\Warframe>msiexec /i Warframe.msi 
Warframe.msi        100%[===================>]  34.75M   308KB/s    in 1m 50s  

2017-10-21 23:35:17 (323 KB/s) - ‘Warframe.msi’ saved [36442112/36442112]

Sorry, still doesn't work........

**Comment by GloriousEggroll** [comment]
your wineprefix is wrong:
"WINEPREFIX=/.wine32"

**Comment by GloriousEggroll** [comment]
also youll need to re-download and update the script, as i added dx10:1 and dx11:1 flags to this:

"start /b /wait "" "C:\Program Files\Warframe\Downloaded\Public\Warframe.exe" -log:/Preprocess.log -threadedworker:1 -cluster:public -language:en -applet:/EE/Types/Framework/ContentUpdate"

https://github.com/GloriousEggroll/warframe-linux/commit/e468d57027b464d790a8c9be89c72e848c4afbaa

but you need to make sure you install to a clean prefix first.

the warframe script prefix should be /home/username/warframe
the lutris prefix should be /home/username/Games/warframe

**Comment by HaZine** [comment]
I'm proper annoyed now. I think it might be from using the wrong prefix, but the lutris version, which was working before is now broken....... it renews the client agreement and then stops on "update on di" after I accept the agreement

**Comment by GloriousEggroll** [comment]
update on di is an error due to a bad prefix or missing dependencies.

you can copy your /prefix/drive_c/Program Files/Warframe/Downloaded folder somewhere else so you dont have to re-download the game

then remove warframe in lutris and run the install script again, then move the Downloaded folder back to
/prefix/drive_c/Program Files/Warframe/

**Comment by HaZine** [comment]
So sorry, holidays with no wifi makes me cry. Ye I fixed the lutris version, and the other version is running. But I've only ran the latter to the point where it starts updating, not sure if there is any bugs or not.
