### ISSUE TITLE
Game crashes during loading screen

### ISSUE THREAD

**Issue by Zeioth** [GloriousEggroll/warframe-linux#51]
The game is installed correctly but after it launchs, it crashes during the loading screen at, about 60%.

![wf](https://user-images.githubusercontent.com/3357792/39495241-cece7a76-4d99-11e8-9d2f-d9ebd5201a46.png)
![wf2](https://user-images.githubusercontent.com/3357792/39495168-834d9a5a-4d99-11e8-8905-ac5ba4761ac7.png)

**Comment by GloriousEggroll** [comment]
I don't have this problem, try disabling the lutris runtime and/or terminal. also try launching the game without lutris. Also check your wine dependencies:
https://www.gloriouseggroll.tv/how-to-get-out-of-wine-dependency-hell/

**Comment by GloriousEggroll** [comment]
#51
https://github.com/GloriousEggroll/warframe-linux/blob/master/README.md
