### ISSUE TITLE
Opens and crashes instantly

### ISSUE THREAD

**Issue by Ravencoin-Miner** [GloriousEggroll/warframe-linux#52]
Double click Warframe in Lutris
Opens updater
Opens optimizer
Both finish
Everything closes and Warframe never launches

Ubuntu 18.04
Latest Lutris
Wine 3.7 Staging

Please let me know what other information I might need to provide.

**Comment by GloriousEggroll** [comment]
please stop

**Comment by GloriousEggroll** [comment]
https://github.com/GloriousEggroll/warframe-linux/issues/51

**Comment by Ravencoin-Miner** [comment]
Tried enabling/disabling runtime as well as terminal. Nothing. Game doesn't even get as far as launcher. It only does the two black boxes.
Running directly from launcher.exe crashes when trying to update direct x and it says 

Update of Di
